//! The filesystem and installed-package contract of the guest image.
//!
//! The image builder and the binary that answers Lambda `MicroVM` build hooks share
//! these values. Keeping the contract in the credential-free guest crate prevents
//! a generated `Dockerfile` from promising checks the shipped agent does not make.

use serde::{Deserialize, Serialize};

/// Where the shipped guest binary lives.
pub const AGENT_PATH: &str = "/opt/aex/hands-agent";

/// Where the inspectable software inventories live.
pub const SBOM_DIR: &str = "/opt/aex/sbom";

/// The installed-package listing generated by the image build.
pub const RPM_LIST_PATH: &str = "/opt/aex/sbom/rpm-nevra.txt";

/// The package lock generated from the same sorted RPM listing.
pub const IMAGE_LOCK_PATH: &str = "/opt/aex/sbom/image.lock.json";

/// The Rust dependency inventory embedded beside the binary.
pub const AGENT_SBOM_PATH: &str = "/opt/aex/sbom/agent.cdx.json";

/// One required rootfs entry.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RootfsEntry {
    /// Absolute path inside the guest.
    pub path: &'static str,
    /// Required POSIX permission bits.
    pub mode: u32,
    /// Whether the entry must be a directory.
    pub directory: bool,
}

/// Every path the `/ready` image hook verifies before Lambda snapshots the VM.
pub const ROOTFS_CONTRACT: [RootfsEntry; 7] = [
    RootfsEntry {
        path: AGENT_PATH,
        mode: 0o755,
        directory: false,
    },
    RootfsEntry {
        path: SBOM_DIR,
        mode: 0o755,
        directory: true,
    },
    RootfsEntry {
        path: AGENT_SBOM_PATH,
        mode: 0o644,
        directory: false,
    },
    RootfsEntry {
        path: RPM_LIST_PATH,
        mode: 0o644,
        directory: false,
    },
    RootfsEntry {
        path: IMAGE_LOCK_PATH,
        mode: 0o644,
        directory: false,
    },
    RootfsEntry {
        path: crate::boot::GUEST_ROOT,
        mode: 0o755,
        directory: true,
    },
    RootfsEntry {
        path: crate::boot::JOURNAL_ROOT,
        mode: 0o755,
        directory: true,
    },
];

/// Paths and artifacts the clean-cut guest image must not carry.
pub const FORBIDDEN_ROOTFS_PATHS: [&str; 8] = [
    "/opt/aex/customer/bun",
    "/opt/aex/customer/python",
    "/opt/aex/runner-bundle",
    "/opt/aex/customer-process-isolation",
    "/etc/nftables",
    "/etc/nftables.conf",
    "/root/.aws",
    "/opt/aex/credentials",
];

/// `aex.hands-image-lock.v1`.
///
/// The `Dockerfile` emits the sorted NEVRA set after its pinned transaction. The
/// `/validate` hook reads this closed document and independently samples `rpm -qa`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct ImageLock {
    /// Schema discriminator.
    pub schema: String,
    /// Digest-pinned container base used by the `Dockerfile`.
    pub container_base: String,
    /// Exact sorted installed package identities.
    pub packages: Vec<String>,
}

impl ImageLock {
    /// Validate the closed document before comparing it with a live guest.
    ///
    /// # Errors
    /// Returns a stable reason for an unsupported schema, unpinned base, empty,
    /// duplicate, or unsorted package list.
    pub fn validate(&self) -> Result<(), &'static str> {
        if self.schema != "aex.hands-image-lock.v1" {
            return Err("unsupported image-lock schema");
        }
        if !self.container_base.contains("@sha256:") {
            return Err("the image-lock container base is not digest-pinned");
        }
        if self.packages.is_empty() {
            return Err("the image-lock package set is empty");
        }
        if self
            .packages
            .iter()
            .any(|package| package.trim() != package || package.is_empty())
        {
            return Err("the image-lock contains a blank or non-canonical package");
        }
        if self.packages.windows(2).any(|pair| pair[0] >= pair[1]) {
            return Err("the image-lock package set is not strictly sorted");
        }
        Ok(())
    }

    /// Compare the lock with an independently observed sorted package set.
    #[must_use]
    pub fn compare(&self, observed: &[String]) -> LockVerdict {
        let mut missing = Vec::new();
        let mut unexpected = Vec::new();
        let mut locked = self.packages.iter().peekable();
        let mut live = observed.iter().peekable();
        while let (Some(expected), Some(actual)) = (locked.peek(), live.peek()) {
            match expected.cmp(actual) {
                core::cmp::Ordering::Less => {
                    missing.push((*expected).clone());
                    locked.next();
                }
                core::cmp::Ordering::Greater => {
                    unexpected.push((*actual).clone());
                    live.next();
                }
                core::cmp::Ordering::Equal => {
                    locked.next();
                    live.next();
                }
            }
        }
        missing.extend(locked.cloned());
        unexpected.extend(live.cloned());
        if missing.is_empty() && unexpected.is_empty() {
            LockVerdict::Match
        } else {
            LockVerdict::Drift {
                missing,
                unexpected,
            }
        }
    }
}

/// What the independent package comparison found.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LockVerdict {
    /// The guest holds exactly the locked packages in canonical order.
    Match,
    /// At least one locked package is absent or an unlocked one is installed.
    Drift {
        /// Locked but absent.
        missing: Vec<String>,
        /// Installed but unlocked.
        unexpected: Vec<String>,
    },
}

impl LockVerdict {
    /// The build-hook status corresponding to this decision.
    #[must_use]
    pub const fn http_status(&self) -> u16 {
        match self {
            Self::Match => 200,
            Self::Drift { .. } => 503,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{ImageLock, LockVerdict};

    fn lock() -> ImageLock {
        ImageLock {
            schema: "aex.hands-image-lock.v1".to_owned(),
            container_base: "example.invalid/base@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".to_owned(),
            packages: vec![
                "bash-0:5.2.15-1.amzn2023.aarch64".to_owned(),
                "jq-0:1.7-1.amzn2023.aarch64".to_owned(),
            ],
        }
    }

    #[test]
    fn only_a_closed_sorted_nonempty_lock_is_valid() {
        assert_eq!(lock().validate(), Ok(()));
        let mut duplicate = lock();
        duplicate.packages[1] = duplicate.packages[0].clone();
        assert!(duplicate.validate().is_err());
        let mut moving = lock();
        moving.container_base = "example.invalid/base:latest".to_owned();
        assert!(moving.validate().is_err());
    }

    #[test]
    fn either_direction_of_package_drift_fails_validation() {
        let locked = lock();
        assert_eq!(locked.compare(&locked.packages), LockVerdict::Match);
        let observed = vec![
            "bash-0:5.2.15-2.amzn2023.aarch64".to_owned(),
            "jq-0:1.7-1.amzn2023.aarch64".to_owned(),
        ];
        let verdict = locked.compare(&observed);
        assert_eq!(verdict.http_status(), 503);
        assert!(matches!(verdict, LockVerdict::Drift { .. }));
    }

    #[test]
    fn unknown_lock_fields_are_refused() {
        assert!(
            serde_json::from_str::<ImageLock>(
                r#"{"schema":"aex.hands-image-lock.v1","containerBase":"x@sha256:y","packages":["x"],"extra":true}"#,
            )
            .is_err()
        );
    }
}
