//! Generated from `telemetry/registry.toml` by `aex_telemetry_schema::codegen`.
//!
//! Do not edit this file. Change `telemetry/registry.toml` and rerun
//! `cargo run -p aex-telemetry-schema --example regenerate`; the
//! `generated_source_is_byte_identical` test fails if the two disagree.

use crate::spec::{
    AttributeSpec, Cardinality, EventSpec, Instrument, MetricSpec, SpanSpec, Visibility,
};

/// Registry schema version this file was generated from.
pub const SCHEMA_VERSION: &str = "1";

/// Name prefixes owned by the telemetry runtime. Product code may not reuse
/// them; [`ATTRIBUTES`], [`METRICS`], [`SPANS`] and [`EVENTS`] are proved free
/// of them at compile time by the `const` block at the end of this file.
pub const RESERVED_PREFIXES: &[&str] = &["aex.reserved.", "otel.", "telemetry.sdk."];

// --- attribute names -------------------------------------------------------------

/// `aex.activation.id` — Brain activation identifier. Internal only: never a metric dimension.
///
/// Cardinality: `unbounded`. Visibility: `internal`. Maximum length: 36 bytes.
pub const AEX_ACTIVATION_ID: &str = "aex.activation.id";

/// `aex.artifact.digest` — Immutable digest of the artifact the process was built from.
///
/// Cardinality: `bounded`. Visibility: `internal`. Maximum length: 71 bytes.
pub const AEX_ARTIFACT_DIGEST: &str = "aex.artifact.digest";

/// `aex.customer.email` — Customer email address. Declared so the redactor can name and drop it.
///
/// Cardinality: `unbounded`. Visibility: `forbidden`. Maximum length: 254 bytes.
pub const AEX_CUSTOMER_EMAIL: &str = "aex.customer.email";

/// `aex.deployable` — Name of the deployable that emitted the record.
///
/// Cardinality: `fixed`. Visibility: `public`. Maximum length: 48 bytes.
pub const AEX_DEPLOYABLE: &str = "aex.deployable";

/// `aex.error.class` — Stable error class from the public error vocabulary.
///
/// Cardinality: `bounded`. Visibility: `public`. Maximum length: 48 bytes.
pub const AEX_ERROR_CLASS: &str = "aex.error.class";

/// `aex.isolation.count` — Complete number of malformed rows isolated in one bounded recovery pass.
///
/// Cardinality: `bounded`. Visibility: `public`. Maximum length: 10 bytes.
pub const AEX_ISOLATION_COUNT: &str = "aex.isolation.count";

/// `aex.isolation.fingerprint` — Redacted sixteen-hex correlation digest for one isolated row.
///
/// Cardinality: `bounded`. Visibility: `public`. Maximum length: 16 bytes.
pub const AEX_ISOLATION_FINGERPRINT: &str = "aex.isolation.fingerprint";

/// `aex.memory.source` — Interface a memory reading came from, or `unavailable` when none declared a limit.
///
/// Cardinality: `fixed`. Visibility: `public`. Maximum length: 16 bytes.
pub const AEX_MEMORY_SOURCE: &str = "aex.memory.source";

/// `aex.memory.used_percent` — Measured percentage of the task memory limit in use. Absent when no limit is declared.
///
/// Cardinality: `bounded`. Visibility: `public`. Maximum length: 10 bytes.
pub const AEX_MEMORY_USED_PERCENT: &str = "aex.memory.used_percent";

/// `aex.meter` — Usage meter identity, one of the four launch meters.
///
/// Cardinality: `fixed`. Visibility: `public`. Maximum length: 32 bytes.
pub const AEX_METER: &str = "aex.meter";

/// `aex.model` — Model slug within the declared provider.
///
/// Cardinality: `bounded`. Visibility: `public`. Maximum length: 64 bytes.
pub const AEX_MODEL: &str = "aex.model";

/// `aex.operation` — Declared operation name, drawn from the contract route registry.
///
/// Cardinality: `bounded`. Visibility: `public`. Maximum length: 64 bytes.
pub const AEX_OPERATION: &str = "aex.operation";

/// `aex.organization.id` — Organization identifier. Internal only: never a metric dimension.
///
/// Cardinality: `unbounded`. Visibility: `internal`. Maximum length: 36 bytes.
pub const AEX_ORGANIZATION_ID: &str = "aex.organization.id";

/// `aex.otlp.counter` — Which OTLP admission counter one delta reports.
///
/// Cardinality: `fixed`. Visibility: `public`. Maximum length: 32 bytes.
pub const AEX_OTLP_COUNTER: &str = "aex.otlp.counter";

/// `aex.outcome` — Outcome class of an operation: ok, rejected, failed or unknown.
///
/// Cardinality: `fixed`. Visibility: `public`. Maximum length: 8 bytes.
pub const AEX_OUTCOME: &str = "aex.outcome";

/// `aex.payment.instrument` — Payment instrument detail. Declared so the redactor can name and drop it.
///
/// Cardinality: `unbounded`. Visibility: `forbidden`. Maximum length: 0 bytes.
pub const AEX_PAYMENT_INSTRUMENT: &str = "aex.payment.instrument";

/// `aex.plane` — Deployment plane the emitting process belongs to.
///
/// Cardinality: `fixed`. Visibility: `public`. Maximum length: 8 bytes.
pub const AEX_PLANE: &str = "aex.plane";

/// `aex.pressure.previous_state` — Measured memory-pressure state a task left.
///
/// Cardinality: `fixed`. Visibility: `public`. Maximum length: 16 bytes.
pub const AEX_PRESSURE_PREVIOUS_STATE: &str = "aex.pressure.previous_state";

/// `aex.pressure.state` — Measured memory-pressure state a task entered: normal, warning, admission-stop or critical.
///
/// Cardinality: `fixed`. Visibility: `public`. Maximum length: 16 bytes.
pub const AEX_PRESSURE_STATE: &str = "aex.pressure.state";

/// `aex.provider` — Model provider, one of the six admitted BYOK providers.
///
/// Cardinality: `fixed`. Visibility: `public`. Maximum length: 16 bytes.
pub const AEX_PROVIDER: &str = "aex.provider";

/// `aex.region` — AWS region the emitting process is bound to.
///
/// Cardinality: `fixed`. Visibility: `public`. Maximum length: 24 bytes.
pub const AEX_REGION: &str = "aex.region";

/// `aex.request.id` — Inbound request identifier. Internal only: never a metric dimension.
///
/// Cardinality: `unbounded`. Visibility: `internal`. Maximum length: 36 bytes.
pub const AEX_REQUEST_ID: &str = "aex.request.id";

/// `aex.retry.count` — Number of attempts already made for this effect identity.
///
/// Cardinality: `bounded`. Visibility: `public`. Maximum length: 3 bytes.
pub const AEX_RETRY_COUNT: &str = "aex.retry.count";

/// `aex.run.id` — Run identifier. Internal only: never a metric dimension.
///
/// Cardinality: `unbounded`. Visibility: `internal`. Maximum length: 36 bytes.
pub const AEX_RUN_ID: &str = "aex.run.id";

/// `aex.secret.plaintext` — Secret plaintext. Declared so the redactor can name and drop it.
///
/// Cardinality: `unbounded`. Visibility: `forbidden`. Maximum length: 0 bytes.
pub const AEX_SECRET_PLAINTEXT: &str = "aex.secret.plaintext";

/// `aex.session.id` — Session identifier. Internal only: never a metric dimension.
///
/// Cardinality: `unbounded`. Visibility: `internal`. Maximum length: 36 bytes.
pub const AEX_SESSION_ID: &str = "aex.session.id";

/// `aex.stream.counter` — Which per-socket stream counter one aggregate delta reports.
///
/// Cardinality: `fixed`. Visibility: `public`. Maximum length: 24 bytes.
pub const AEX_STREAM_COUNTER: &str = "aex.stream.counter";

/// `aex.workspace.id` — Workspace identifier. Internal only: never a metric dimension.
///
/// Cardinality: `unbounded`. Visibility: `internal`. Maximum length: 36 bytes.
pub const AEX_WORKSPACE_ID: &str = "aex.workspace.id";

/// Every declared attribute, ordered by name.
pub const ATTRIBUTES: &[AttributeSpec] = &[
    AttributeSpec {
        name: AEX_ACTIVATION_ID,
        cardinality: Cardinality::Unbounded,
        visibility: Visibility::Internal,
        max_len: 36,
    },
    AttributeSpec {
        name: AEX_ARTIFACT_DIGEST,
        cardinality: Cardinality::Bounded,
        visibility: Visibility::Internal,
        max_len: 71,
    },
    AttributeSpec {
        name: AEX_CUSTOMER_EMAIL,
        cardinality: Cardinality::Unbounded,
        visibility: Visibility::Forbidden,
        max_len: 254,
    },
    AttributeSpec {
        name: AEX_DEPLOYABLE,
        cardinality: Cardinality::Fixed,
        visibility: Visibility::Public,
        max_len: 48,
    },
    AttributeSpec {
        name: AEX_ERROR_CLASS,
        cardinality: Cardinality::Bounded,
        visibility: Visibility::Public,
        max_len: 48,
    },
    AttributeSpec {
        name: AEX_ISOLATION_COUNT,
        cardinality: Cardinality::Bounded,
        visibility: Visibility::Public,
        max_len: 10,
    },
    AttributeSpec {
        name: AEX_ISOLATION_FINGERPRINT,
        cardinality: Cardinality::Bounded,
        visibility: Visibility::Public,
        max_len: 16,
    },
    AttributeSpec {
        name: AEX_MEMORY_SOURCE,
        cardinality: Cardinality::Fixed,
        visibility: Visibility::Public,
        max_len: 16,
    },
    AttributeSpec {
        name: AEX_MEMORY_USED_PERCENT,
        cardinality: Cardinality::Bounded,
        visibility: Visibility::Public,
        max_len: 10,
    },
    AttributeSpec {
        name: AEX_METER,
        cardinality: Cardinality::Fixed,
        visibility: Visibility::Public,
        max_len: 32,
    },
    AttributeSpec {
        name: AEX_MODEL,
        cardinality: Cardinality::Bounded,
        visibility: Visibility::Public,
        max_len: 64,
    },
    AttributeSpec {
        name: AEX_OPERATION,
        cardinality: Cardinality::Bounded,
        visibility: Visibility::Public,
        max_len: 64,
    },
    AttributeSpec {
        name: AEX_ORGANIZATION_ID,
        cardinality: Cardinality::Unbounded,
        visibility: Visibility::Internal,
        max_len: 36,
    },
    AttributeSpec {
        name: AEX_OTLP_COUNTER,
        cardinality: Cardinality::Fixed,
        visibility: Visibility::Public,
        max_len: 32,
    },
    AttributeSpec {
        name: AEX_OUTCOME,
        cardinality: Cardinality::Fixed,
        visibility: Visibility::Public,
        max_len: 8,
    },
    AttributeSpec {
        name: AEX_PAYMENT_INSTRUMENT,
        cardinality: Cardinality::Unbounded,
        visibility: Visibility::Forbidden,
        max_len: 0,
    },
    AttributeSpec {
        name: AEX_PLANE,
        cardinality: Cardinality::Fixed,
        visibility: Visibility::Public,
        max_len: 8,
    },
    AttributeSpec {
        name: AEX_PRESSURE_PREVIOUS_STATE,
        cardinality: Cardinality::Fixed,
        visibility: Visibility::Public,
        max_len: 16,
    },
    AttributeSpec {
        name: AEX_PRESSURE_STATE,
        cardinality: Cardinality::Fixed,
        visibility: Visibility::Public,
        max_len: 16,
    },
    AttributeSpec {
        name: AEX_PROVIDER,
        cardinality: Cardinality::Fixed,
        visibility: Visibility::Public,
        max_len: 16,
    },
    AttributeSpec {
        name: AEX_REGION,
        cardinality: Cardinality::Fixed,
        visibility: Visibility::Public,
        max_len: 24,
    },
    AttributeSpec {
        name: AEX_REQUEST_ID,
        cardinality: Cardinality::Unbounded,
        visibility: Visibility::Internal,
        max_len: 36,
    },
    AttributeSpec {
        name: AEX_RETRY_COUNT,
        cardinality: Cardinality::Bounded,
        visibility: Visibility::Public,
        max_len: 3,
    },
    AttributeSpec {
        name: AEX_RUN_ID,
        cardinality: Cardinality::Unbounded,
        visibility: Visibility::Internal,
        max_len: 36,
    },
    AttributeSpec {
        name: AEX_SECRET_PLAINTEXT,
        cardinality: Cardinality::Unbounded,
        visibility: Visibility::Forbidden,
        max_len: 0,
    },
    AttributeSpec {
        name: AEX_SESSION_ID,
        cardinality: Cardinality::Unbounded,
        visibility: Visibility::Internal,
        max_len: 36,
    },
    AttributeSpec {
        name: AEX_STREAM_COUNTER,
        cardinality: Cardinality::Fixed,
        visibility: Visibility::Public,
        max_len: 24,
    },
    AttributeSpec {
        name: AEX_WORKSPACE_ID,
        cardinality: Cardinality::Unbounded,
        visibility: Visibility::Internal,
        max_len: 36,
    },
];

// --- instrument names ------------------------------------------------------------

/// `aex.admission.rejected` — Admissions shed by a pressure or quota policy.
///
/// Instrument: `counter`. Unit: `1`.
pub const METRIC_AEX_ADMISSION_REJECTED: &str = "aex.admission.rejected";

/// `aex.operation.duration` — Wall-clock duration of a declared operation.
///
/// Instrument: `histogram`. Unit: `ms`.
pub const METRIC_AEX_OPERATION_DURATION: &str = "aex.operation.duration";

/// `aex.otlp.count` — Delta of one named OTLP admission counter.
///
/// Instrument: `counter`. Unit: `1`.
pub const METRIC_AEX_OTLP_COUNT: &str = "aex.otlp.count";

/// `aex.stream.bytes` — Aggregate delta of authority bytes returned to open stream sockets since the previous publication.
///
/// Instrument: `counter`. Unit: `By`.
pub const METRIC_AEX_STREAM_BYTES: &str = "aex.stream.bytes";

/// `aex.stream.count` — Aggregate delta of one named per-socket stream counter since the previous publication.
///
/// Instrument: `counter`. Unit: `1`.
pub const METRIC_AEX_STREAM_COUNT: &str = "aex.stream.count";

/// `aex.telemetry.flush.deadline.exceeded` — Flush attempts that stopped at their deadline with records still pending.
///
/// Instrument: `counter`. Unit: `1`.
pub const METRIC_AEX_TELEMETRY_FLUSH_DEADLINE_EXCEEDED: &str =
    "aex.telemetry.flush.deadline.exceeded";

/// `aex.telemetry.records.dropped` — Diagnostic records discarded because the bounded export queue was full or the exporter failed.
///
/// Instrument: `counter`. Unit: `1`.
pub const METRIC_AEX_TELEMETRY_RECORDS_DROPPED: &str = "aex.telemetry.records.dropped";

/// `aex.telemetry.records.exported` — Diagnostic records handed to the host exporter.
///
/// Instrument: `counter`. Unit: `1`.
pub const METRIC_AEX_TELEMETRY_RECORDS_EXPORTED: &str = "aex.telemetry.records.exported";

/// Every declared instrument, ordered by name.
pub const METRICS: &[MetricSpec] = &[
    MetricSpec {
        name: METRIC_AEX_ADMISSION_REJECTED,
        instrument: Instrument::Counter,
        unit: "1",
        attributes: &[AEX_DEPLOYABLE, AEX_ERROR_CLASS, AEX_PLANE, AEX_REGION],
    },
    MetricSpec {
        name: METRIC_AEX_OPERATION_DURATION,
        instrument: Instrument::Histogram,
        unit: "ms",
        attributes: &[
            AEX_DEPLOYABLE,
            AEX_OPERATION,
            AEX_OUTCOME,
            AEX_PLANE,
            AEX_REGION,
        ],
    },
    MetricSpec {
        name: METRIC_AEX_OTLP_COUNT,
        instrument: Instrument::Counter,
        unit: "1",
        attributes: &[AEX_DEPLOYABLE, AEX_OTLP_COUNTER, AEX_PLANE, AEX_REGION],
    },
    MetricSpec {
        name: METRIC_AEX_STREAM_BYTES,
        instrument: Instrument::Counter,
        unit: "By",
        attributes: &[AEX_DEPLOYABLE, AEX_PLANE, AEX_REGION],
    },
    MetricSpec {
        name: METRIC_AEX_STREAM_COUNT,
        instrument: Instrument::Counter,
        unit: "1",
        attributes: &[AEX_DEPLOYABLE, AEX_PLANE, AEX_REGION, AEX_STREAM_COUNTER],
    },
    MetricSpec {
        name: METRIC_AEX_TELEMETRY_FLUSH_DEADLINE_EXCEEDED,
        instrument: Instrument::Counter,
        unit: "1",
        attributes: &[AEX_DEPLOYABLE, AEX_PLANE, AEX_REGION],
    },
    MetricSpec {
        name: METRIC_AEX_TELEMETRY_RECORDS_DROPPED,
        instrument: Instrument::Counter,
        unit: "1",
        attributes: &[AEX_DEPLOYABLE, AEX_PLANE, AEX_REGION],
    },
    MetricSpec {
        name: METRIC_AEX_TELEMETRY_RECORDS_EXPORTED,
        instrument: Instrument::Counter,
        unit: "1",
        attributes: &[AEX_DEPLOYABLE, AEX_PLANE, AEX_REGION],
    },
];

// --- span names ------------------------------------------------------------------

/// `aex.operation.execute` — One declared operation from admission to outcome.
pub const SPAN_AEX_OPERATION_EXECUTE: &str = "aex.operation.execute";

/// `aex.provider.call` — One model provider request, including its streamed response.
pub const SPAN_AEX_PROVIDER_CALL: &str = "aex.provider.call";

/// `aex.storage.transaction` — One durable storage transaction against a single authority.
pub const SPAN_AEX_STORAGE_TRANSACTION: &str = "aex.storage.transaction";

/// Every declared span, ordered by name.
pub const SPANS: &[SpanSpec] = &[
    SpanSpec {
        name: SPAN_AEX_OPERATION_EXECUTE,
        attributes: &[AEX_ERROR_CLASS, AEX_OPERATION, AEX_OUTCOME, AEX_RETRY_COUNT],
    },
    SpanSpec {
        name: SPAN_AEX_PROVIDER_CALL,
        attributes: &[AEX_ERROR_CLASS, AEX_MODEL, AEX_OUTCOME, AEX_PROVIDER],
    },
    SpanSpec {
        name: SPAN_AEX_STORAGE_TRANSACTION,
        attributes: &[AEX_ERROR_CLASS, AEX_OPERATION, AEX_OUTCOME, AEX_RETRY_COUNT],
    },
];

// --- event names -----------------------------------------------------------------

/// `aex.brain.due_row.isolated` — Brain isolated a malformed due-index row while valid siblings continued.
pub const EVENT_AEX_BRAIN_DUE_ROW_ISOLATED: &str = "aex.brain.due_row.isolated";

/// `aex.brain.memory_pressure.transitioned` — Brain crossed a measured memory watermark, or lost or regained the ability to measure one.
pub const EVENT_AEX_BRAIN_MEMORY_PRESSURE_TRANSITIONED: &str =
    "aex.brain.memory_pressure.transitioned";

/// `aex.process.configuration.rejected` — A deployable refused to start because its configuration was invalid.
pub const EVENT_AEX_PROCESS_CONFIGURATION_REJECTED: &str = "aex.process.configuration.rejected";

/// `aex.process.started` — A deployable accepted its configuration and started.
pub const EVENT_AEX_PROCESS_STARTED: &str = "aex.process.started";

/// `aex.telemetry.exporter.absent` — No exporter was installed, so diagnostics are discarded at the facade.
pub const EVENT_AEX_TELEMETRY_EXPORTER_ABSENT: &str = "aex.telemetry.exporter.absent";

/// Every declared event, ordered by name.
pub const EVENTS: &[EventSpec] = &[
    EventSpec {
        name: EVENT_AEX_BRAIN_DUE_ROW_ISOLATED,
        attributes: &[
            AEX_DEPLOYABLE,
            AEX_ERROR_CLASS,
            AEX_ISOLATION_COUNT,
            AEX_ISOLATION_FINGERPRINT,
            AEX_PLANE,
            AEX_REGION,
        ],
    },
    EventSpec {
        name: EVENT_AEX_BRAIN_MEMORY_PRESSURE_TRANSITIONED,
        attributes: &[
            AEX_DEPLOYABLE,
            AEX_MEMORY_SOURCE,
            AEX_MEMORY_USED_PERCENT,
            AEX_PLANE,
            AEX_PRESSURE_PREVIOUS_STATE,
            AEX_PRESSURE_STATE,
            AEX_REGION,
        ],
    },
    EventSpec {
        name: EVENT_AEX_PROCESS_CONFIGURATION_REJECTED,
        attributes: &[AEX_DEPLOYABLE, AEX_ERROR_CLASS, AEX_PLANE, AEX_REGION],
    },
    EventSpec {
        name: EVENT_AEX_PROCESS_STARTED,
        attributes: &[AEX_ARTIFACT_DIGEST, AEX_DEPLOYABLE, AEX_PLANE, AEX_REGION],
    },
    EventSpec {
        name: EVENT_AEX_TELEMETRY_EXPORTER_ABSENT,
        attributes: &[AEX_DEPLOYABLE, AEX_PLANE, AEX_REGION],
    },
];

// --- compile-time reserved-name rule ---------------------------------------------

// Every declared name is proved free of every reserved prefix while the crate is
// compiled, so a reserved-prefix collision can never reach a running process.
const _: () = {
    let mut index = 0;
    while index < ATTRIBUTES.len() {
        assert!(
            !crate::reserved::matches_any(ATTRIBUTES[index].name, RESERVED_PREFIXES),
            "an attribute name reuses a reserved prefix"
        );
        index += 1;
    }
    let mut index = 0;
    while index < METRICS.len() {
        assert!(
            !crate::reserved::matches_any(METRICS[index].name, RESERVED_PREFIXES),
            "a metric name reuses a reserved prefix"
        );
        index += 1;
    }
    let mut index = 0;
    while index < SPANS.len() {
        assert!(
            !crate::reserved::matches_any(SPANS[index].name, RESERVED_PREFIXES),
            "a span name reuses a reserved prefix"
        );
        index += 1;
    }
    let mut index = 0;
    while index < EVENTS.len() {
        assert!(
            !crate::reserved::matches_any(EVENTS[index].name, RESERVED_PREFIXES),
            "an event name reuses a reserved prefix"
        );
        index += 1;
    }
};
