// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"changelog.md": () => import("../content/docs/changelog.md?collection=docs"), "examples.md": () => import("../content/docs/examples.md?collection=docs"), "features.md": () => import("../content/docs/features.md?collection=docs"), "index.md": () => import("../content/docs/index.md?collection=docs"), "integrations.md": () => import("../content/docs/integrations.md?collection=docs"), "support.md": () => import("../content/docs/support.md?collection=docs"), "concepts/agent-tools.md": () => import("../content/docs/concepts/agent-tools.md?collection=docs"), "concepts/composition.md": () => import("../content/docs/concepts/composition.md?collection=docs"), "concepts/sessions.md": () => import("../content/docs/concepts/sessions.md?collection=docs"), "reference/api.md": () => import("../content/docs/reference/api.md?collection=docs"), "reference/cli.md": () => import("../content/docs/reference/cli.md?collection=docs"), "reference/index.md": () => import("../content/docs/reference/index.md?collection=docs"), "guides/authentication.md": () => import("../content/docs/guides/authentication.md?collection=docs"), "guides/billing.md": () => import("../content/docs/guides/billing.md?collection=docs"), "guides/errors.md": () => import("../content/docs/guides/errors.md?collection=docs"), "guides/files.md": () => import("../content/docs/guides/files.md?collection=docs"), "guides/limits.md": () => import("../content/docs/guides/limits.md?collection=docs"), "guides/networking.md": () => import("../content/docs/guides/networking.md?collection=docs"), "guides/quickstart.md": () => import("../content/docs/guides/quickstart.md?collection=docs"), "guides/release.md": () => import("../content/docs/guides/release.md?collection=docs"), "guides/resources.md": () => import("../content/docs/guides/resources.md?collection=docs"), "guides/retries.md": () => import("../content/docs/guides/retries.md?collection=docs"), "guides/telemetry.md": () => import("../content/docs/guides/telemetry.md?collection=docs"), "guides/testing.md": () => import("../content/docs/guides/testing.md?collection=docs"), "reference/sdk/index.md": () => import("../content/docs/reference/sdk/index.md?collection=docs"), }),
};
export default browserCollections;