//! The generated TypeScript wire models and validators.
//!
//! This is a second language binding of the same [`ContractIr`](crate::ir::ContractIr)
//! that emits `aex-wire`; it does not parse or restate the authored schema tree.

use std::collections::{BTreeMap, BTreeSet};

use crate::ir::{ContractIr, FieldType, SchemaBody, SchemaIr};

/// Renders `packages/wire/src/generated/models.ts`.
#[must_use]
pub fn typescript_wire(ir: &ContractIr, digest: &str) -> String {
    let mut out = String::new();
    out.push_str("// @generated by aex-contract-gen; DO NOT EDIT.\n");
    out.push_str(&format!("// Contract digest: {digest}\n\n"));
    out.push_str("import { z } from \"zod\";\n\n");
    out.push_str(&format!(
        "export const CONTRACT_DIGEST = {} as const;\n\n",
        quoted(digest)
    ));
    emit_identifiers(ir, &mut out);
    emit_scalar_helpers(&mut out);
    emit_recursive_union_types(ir, &mut out);

    let manual_types = recursive_type_ids(ir);

    for schema in schemas_in_dependency_order(ir) {
        emit_schema(ir, schema, &manual_types, &mut out);
    }
    out
}

fn emit_recursive_union_types(ir: &ContractIr, out: &mut String) {
    out.push_str("export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n\n");
    for schema in ir.schemas.values() {
        let SchemaBody::Union { tag, variants } = &schema.body else {
            continue;
        };
        if !is_recursive_union(ir, &schema.id) {
            continue;
        }
        for variant in variants {
            let payload = &ir.schemas[&variant.payload];
            let SchemaBody::Object { fields } = &payload.body else {
                panic!("union payload {} is not an object", payload.id);
            };
            out.push_str(&format!("export interface {} {{\n", payload.id));
            for field in fields {
                out.push_str(&format!(
                    "  readonly {}{}: {};\n",
                    quoted(&field.wire),
                    if field.optional { "?" } else { "" },
                    typescript_type(ir, &field.ty)
                ));
            }
            out.push_str("}\n");
        }
        let arms = variants
            .iter()
            .map(|variant| {
                format!(
                    "({} & {{ readonly {}: {} }})",
                    variant.payload,
                    quoted(tag),
                    quoted(&variant.value)
                )
            })
            .collect::<Vec<_>>()
            .join(" | ");
        out.push_str(&format!("export type {} = {arms};\n\n", schema.id));
    }
}

fn recursive_type_ids(ir: &ContractIr) -> BTreeSet<String> {
    let mut ids = BTreeSet::new();
    for schema in ir.schemas.values() {
        let SchemaBody::Union { variants, .. } = &schema.body else {
            continue;
        };
        if !is_recursive_union(ir, &schema.id) {
            continue;
        }
        ids.insert(schema.id.clone());
        ids.extend(variants.iter().map(|variant| variant.payload.clone()));
    }
    ids
}

fn is_recursive_union(ir: &ContractIr, union_id: &str) -> bool {
    let Some(SchemaIr {
        body: SchemaBody::Union { variants, .. },
        ..
    }) = ir.schemas.get(union_id)
    else {
        return false;
    };
    variants.iter().any(|variant| {
        ir.schemas
            .get(&variant.payload)
            .is_some_and(|payload| schema_references(payload, union_id))
    })
}

fn schema_references(schema: &SchemaIr, target: &str) -> bool {
    match &schema.body {
        SchemaBody::Object { fields } => fields
            .iter()
            .any(|field| typescript_dependency(&field.ty) == Some(target)),
        SchemaBody::Union { variants, .. } => {
            variants.iter().any(|variant| variant.payload == target)
        }
        SchemaBody::Enum { .. } => false,
    }
}

fn emit_identifiers(ir: &ContractIr, out: &mut String) {
    out.push_str("export const ID_PREFIXES = {\n");
    for row in &ir.ids {
        out.push_str(&format!("  {}: {},\n", row.key, quoted(&row.prefix)));
    }
    out.push_str("} as const;\n");
    out.push_str("export type IdKind = keyof typeof ID_PREFIXES;\n");
    out.push_str(
        "export type Id<K extends IdKind = IdKind> = `${(typeof ID_PREFIXES)[K]}_${string}`;\n",
    );
    out.push_str("export const ID_KINDS = Object.freeze(Object.keys(ID_PREFIXES) as IdKind[]);\n");
    out.push_str("const ID_BODY_PATTERN = \"[0-9a-hjkmnp-tv-z]{26}\";\n");
    out.push_str("const ID_PATTERNS = new Map<IdKind, RegExp>();\n");
    out.push_str("const CROCKFORD = \"0123456789abcdefghjkmnpqrstvwxyz\";\n");
    out.push_str("export function idPatternSource(kind: IdKind): string { return `^${ID_PREFIXES[kind]}_${ID_BODY_PATTERN}$`; }\n");
    out.push_str("export function idPattern(kind: IdKind): RegExp { const found = ID_PATTERNS.get(kind); if (found) return found; const pattern = new RegExp(idPatternSource(kind)); ID_PATTERNS.set(kind, pattern); return pattern; }\n");
    out.push_str("function isUuidV7Body(value: string): boolean { let encoded = 0n; for (const character of value) { const digit = CROCKFORD.indexOf(character); if (digit < 0) return false; encoded = (encoded << 5n) | BigInt(digit); } if (encoded >= (1n << 128n)) return false; const bytes = new Uint8Array(16); for (let index = 15; index >= 0; index -= 1) { bytes[index] = Number(encoded & 255n); encoded >>= 8n; } return (bytes[6]! & 0xf0) === 0x70 && (bytes[8]! & 0xc0) === 0x80; }\n");
    out.push_str("export function isId<K extends IdKind>(kind: K, value: unknown): value is Id<K> { return typeof value === \"string\" && idPattern(kind).test(value) && isUuidV7Body(value.slice(value.indexOf(\"_\") + 1)); }\n");
    out.push_str("export function assertId<K extends IdKind>(kind: K, value: unknown, label = `${kind} id`): Id<K> { if (isId(kind, value)) return value; const got = typeof value === \"string\" ? JSON.stringify(value) : `<${typeof value}>`; throw new Error(`${label} must match ${idPatternSource(kind)}, got ${got}`); }\n");
    out.push_str("function toBase32(bytes: Uint8Array): string { let value = 0n; for (const byte of bytes) value = (value << 8n) | BigInt(byte); let result = \"\"; for (let index = 0; index < 26; index += 1) { result = CROCKFORD[Number(value & 31n)]! + result; value >>= 5n; } return result; }\n");
    out.push_str("export function newId<K extends IdKind>(kind: K): Id<K> { const prefix = ID_PREFIXES[kind]; const crypto = globalThis.crypto; if (prefix === undefined) throw new Error(`newId: unknown id kind ${String(kind)}`); if (typeof crypto?.getRandomValues !== \"function\") throw new Error(\"newId: crypto.getRandomValues is unavailable\"); const bytes = crypto.getRandomValues(new Uint8Array(16)); const timestamp = Date.now(); bytes[0] = Math.floor(timestamp / 2 ** 40) & 0xff; bytes[1] = Math.floor(timestamp / 2 ** 32) & 0xff; bytes[2] = Math.floor(timestamp / 2 ** 24) & 0xff; bytes[3] = Math.floor(timestamp / 2 ** 16) & 0xff; bytes[4] = Math.floor(timestamp / 2 ** 8) & 0xff; bytes[5] = timestamp & 0xff; bytes[6] = (bytes[6]! & 0x0f) | 0x70; bytes[8] = (bytes[8]! & 0x3f) | 0x80; return `${prefix}_${toBase32(bytes)}` as Id<K>; }\n\n");
}

fn emit_scalar_helpers(out: &mut String) {
    out.push_str("const utf8 = new TextEncoder();\n");
    out.push_str("function boundedText(min: number, max: number, pattern?: RegExp) { let schema = z.string().refine((value) => { const length = utf8.encode(value).byteLength; return length >= min && length <= max; }, { message: `must be ${min}..=${max} UTF-8 bytes` }); if (pattern) schema = schema.refine((value) => pattern.test(value), { message: `must match ${pattern.source}` }); return schema; }\n");
    out.push_str("const timestamp = z.string().regex(/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$/).refine((value) => { const parsed = new Date(value); return !Number.isNaN(parsed.valueOf()) && parsed.toISOString() === value; }, { message: \"must be a real RFC 3339 UTC millisecond instant\" });\n");
    out.push_str("const decimal = z.string().regex(/^(0|[1-9]\\d*)$/);\n");
    out.push_str("const region = z.enum([\"us-east-1\", \"us-east-2\", \"us-west-2\", \"ap-northeast-1\", \"eu-west-1\"]);\n");
    out.push_str("const computeSize = z.enum([\"512mb\", \"1gb\", \"2gb\", \"4gb\", \"8gb\"]);\n");
    out.push_str("const contentHash = z.string().regex(/^sha256:[0-9a-f]{64}$/);\n");
    out.push_str("const resourceName = z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/);\n");
    out.push_str("const filePath = boundedText(1, 4096).refine((value) => value === \"/\" || (value.startsWith(\"/\") && !value.slice(1).split(\"/\").some((part) => part === \"\" || part === \".\" || part === \"..\") && !/[\\u0000-\\u001f\\u007f]/.test(value)), { message: \"must be a normalized absolute POSIX path\" });\n");
    out.push_str("const httpsUrl = boundedText(1, 2048).refine((value) => { if (!value.startsWith(\"https://\") || /[\\u0000-\\u001f\\u007f]/.test(value)) return false; return (value.slice(8).split(/[/?#]/, 1)[0]?.length ?? 0) > 0; }, { message: \"must be an absolute https URL\" });\n");
    out.push_str("const jsonPointer = z.string().refine((value) => (value === \"\" || value.startsWith(\"/\")) && !/[\\u0000-\\u001f\\u007f]/.test(value) && !/(^|[^~])~(?:[^01]|$)/.test(value), { message: \"must be an RFC 6901 JSON pointer\" });\n");
    out.push_str(
        "const metadataValue = z.union([z.string(), z.number(), z.boolean(), z.null()]);\n\n",
    );
}

fn schemas_in_dependency_order(ir: &ContractIr) -> Vec<&SchemaIr> {
    let mut remaining: BTreeMap<&str, &SchemaIr> = ir
        .schemas
        .values()
        .map(|schema| (schema.id.as_str(), schema))
        .collect();
    let mut emitted = BTreeSet::new();
    let mut ordered = Vec::with_capacity(remaining.len());
    while !remaining.is_empty() {
        let next = remaining
            .iter()
            .find(|(_, schema)| schema_dependencies(ir, schema).is_subset(&emitted))
            .map_or_else(
                || panic!("TypeScript schema dependency cycle: {:?}", remaining.keys()),
                |(id, _)| *id,
            );
        let schema = remaining.remove(next).expect("selected schema exists");
        emitted.insert(next.to_owned());
        ordered.push(schema);
    }
    ordered
}

fn schema_dependencies(ir: &ContractIr, schema: &SchemaIr) -> BTreeSet<String> {
    let mut dependencies = BTreeSet::new();
    match &schema.body {
        SchemaBody::Object { fields } => {
            for field in fields {
                if let Some(id) = typescript_dependency(&field.ty)
                    && !is_union_back_edge(ir, &schema.id, id)
                {
                    dependencies.insert(id.to_owned());
                }
            }
        }
        SchemaBody::Union { variants, .. } => {
            dependencies.extend(variants.iter().map(|variant| variant.payload.clone()));
        }
        SchemaBody::Enum { .. } => {}
    }
    dependencies.remove(&schema.id);
    dependencies
}

fn typescript_dependency(ty: &FieldType) -> Option<&str> {
    match ty {
        FieldType::ByteRange => Some("ByteRange"),
        FieldType::ProviderId => Some("ProviderId"),
        _ => ty.referenced_schema(),
    }
}

/// A union arm may contain the union recursively. The arm must be emitted first
/// so the union can call `.extend`, while the arm's reference is evaluated only
/// when validation runs, after module initialization.
fn is_union_back_edge(ir: &ContractIr, owner: &str, referenced: &str) -> bool {
    matches!(
        ir.schemas.get(referenced).map(|schema| &schema.body),
        Some(SchemaBody::Union { variants, .. })
            if variants.iter().any(|variant| variant.payload == owner)
    )
}

fn emit_schema(
    ir: &ContractIr,
    schema: &SchemaIr,
    manual_types: &BTreeSet<String>,
    out: &mut String,
) {
    out.push_str(&format!("/** {} */\n", schema.doc.replace("*/", "* /")));
    match &schema.body {
        SchemaBody::Object { fields } => {
            out.push_str(&format!("export const {}Schema = z.object({{\n", schema.id));
            for field in fields {
                let mut expression = zod_type(ir, &schema.id, &field.ty);
                if field.optional {
                    expression.push_str(".optional()");
                }
                out.push_str(&format!("  {}: {},\n", quoted(&field.wire), expression));
            }
            if schema.id == "ByteRange" {
                out.push_str("}).strict().refine((value) => BigInt(value.endInclusive) >= BigInt(value.start), { message: \"endInclusive must not precede start\" });\n");
            } else {
                out.push_str("}).strict();\n");
            }
        }
        SchemaBody::Enum { values } => {
            let values = values
                .iter()
                .map(|value| quoted(&value.value))
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!(
                "export const {}Schema = z.enum([{values}]);\n",
                schema.id
            ));
            out.push_str(&format!(
                "export const {}Values = {}Schema.options;\n",
                schema.id, schema.id
            ));
        }
        SchemaBody::Union { tag, variants } => {
            let arms = variants
                .iter()
                .map(|variant| {
                    format!(
                        "{}Schema.extend({{ {}: z.literal({}) }})",
                        variant.payload,
                        quoted(tag),
                        quoted(&variant.value)
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            let annotation = if is_recursive_union(ir, &schema.id) {
                format!(": z.ZodType<{}>", schema.id)
            } else {
                String::new()
            };
            out.push_str(&format!(
                "export const {}Schema{annotation} = z.discriminatedUnion({}, [{arms}]);\n",
                schema.id,
                quoted(tag)
            ));
        }
    }
    if manual_types.contains(&schema.id) {
        out.push('\n');
    } else {
        out.push_str(&format!(
            "export type {} = z.infer<typeof {}Schema>;\n\n",
            schema.id, schema.id
        ));
    }
}

fn typescript_type(ir: &ContractIr, ty: &FieldType) -> String {
    match ty {
        FieldType::Text { .. }
        | FieldType::Id(_)
        | FieldType::Timestamp
        | FieldType::Decimal
        | FieldType::Cents
        | FieldType::ContentHash
        | FieldType::ResourceName
        | FieldType::FilePath
        | FieldType::TraceId
        | FieldType::SpanId
        | FieldType::HttpsUrl
        | FieldType::ETag
        | FieldType::Cursor
        | FieldType::JsonPointer => "string".to_owned(),
        FieldType::Integer { .. } | FieldType::Float => "number".to_owned(),
        FieldType::Bool => "boolean".to_owned(),
        FieldType::Ref(id) => id.clone(),
        FieldType::Array(inner, _) => format!("{}[]", typescript_type(ir, inner)),
        FieldType::Map(inner) => format!("Record<string, {}>", typescript_type(ir, inner)),
        FieldType::Region => {
            "\"us-east-1\" | \"us-east-2\" | \"us-west-2\" | \"ap-northeast-1\" | \"eu-west-1\""
                .to_owned()
        }
        FieldType::ComputeSize => "\"512mb\" | \"1gb\" | \"2gb\" | \"4gb\" | \"8gb\"".to_owned(),
        FieldType::CanonicalJson => "JsonValue".to_owned(),
        FieldType::ByteRange => "ByteRange".to_owned(),
        FieldType::ProviderId => "ProviderId".to_owned(),
        FieldType::Scope => union_type(ir.scopes.iter().map(|row| row.scope.as_str())),
        FieldType::LimitId => union_type(ir.limits.iter().map(|row| row.id.as_str())),
        FieldType::ErrorCode => union_type(ir.errors.iter().map(|row| row.code.as_str())),
        FieldType::MetadataValue => "string | number | boolean | null".to_owned(),
    }
}

fn union_type<'a>(values: impl Iterator<Item = &'a str>) -> String {
    values.map(quoted).collect::<Vec<_>>().join(" | ")
}

fn zod_type(ir: &ContractIr, owner: &str, ty: &FieldType) -> String {
    match ty {
        FieldType::Text { min, max, pattern } => format!(
            "boundedText({min}, {max}, {})",
            pattern.as_ref().map_or_else(
                || "undefined".to_owned(),
                |value| format!("new RegExp({})", quoted(value)),
            )
        ),
        FieldType::Id(key) => format!(
            "z.string().refine((value) => isId({}, value), {{ message: \"must be a valid UUIDv7 identifier\" }})",
            quoted(key)
        ),
        FieldType::Timestamp => "timestamp".to_owned(),
        FieldType::Decimal | FieldType::Cents => "decimal".to_owned(),
        FieldType::Integer { min, max } => format!("z.number().int().min({min}).max({max})"),
        FieldType::Float => "z.number().finite()".to_owned(),
        FieldType::Bool => "z.boolean()".to_owned(),
        FieldType::Ref(id) if is_union_back_edge(ir, owner, id) => {
            format!("z.lazy((): z.ZodType<{id}> => {id}Schema)")
        }
        FieldType::Ref(id) => format!("{id}Schema"),
        FieldType::Array(inner, max) => {
            format!("z.array({}).max({max})", zod_type(ir, owner, inner))
        }
        FieldType::Map(inner) => {
            format!("z.record(z.string(), {})", zod_type(ir, owner, inner))
        }
        FieldType::Region => "region".to_owned(),
        FieldType::ComputeSize => "computeSize".to_owned(),
        FieldType::ContentHash => "contentHash".to_owned(),
        FieldType::ResourceName => "resourceName".to_owned(),
        FieldType::FilePath => "filePath".to_owned(),
        FieldType::TraceId => {
            "z.string().regex(/^[0-9a-f]{32}$/).refine((value) => !/^0+$/.test(value), { message: \"all-zero trace id is invalid\" })".to_owned()
        }
        FieldType::SpanId => {
            "z.string().regex(/^[0-9a-f]{16}$/).refine((value) => !/^0+$/.test(value), { message: \"all-zero span id is invalid\" })".to_owned()
        }
        FieldType::HttpsUrl => "httpsUrl".to_owned(),
        FieldType::ETag => "boundedText(1, 256).refine((value) => !/[\\u0000-\\u001f\\u007f]/.test(value), { message: \"must not contain control characters\" })".to_owned(),
        FieldType::Cursor => {
            "boundedText(5, 4096, /^cur_[A-Za-z0-9_-]+(?:\\.[A-Za-z0-9_-]+)?$/)".to_owned()
        }
        FieldType::JsonPointer => "jsonPointer".to_owned(),
        FieldType::CanonicalJson => "z.json()".to_owned(),
        FieldType::ByteRange => "ByteRangeSchema".to_owned(),
        FieldType::ProviderId => "ProviderIdSchema".to_owned(),
        FieldType::Scope => zod_registry(ir.scopes.iter().map(|row| row.scope.as_str())),
        FieldType::LimitId => zod_registry(ir.limits.iter().map(|row| row.id.as_str())),
        FieldType::ErrorCode => zod_registry(ir.errors.iter().map(|row| row.code.as_str())),
        FieldType::MetadataValue => "metadataValue".to_owned(),
    }
}

fn zod_registry<'a>(values: impl Iterator<Item = &'a str>) -> String {
    format!(
        "z.enum([{}])",
        values.map(quoted).collect::<Vec<_>>().join(", ")
    )
}

fn quoted(value: &str) -> String {
    serde_json::to_string(value).expect("a string always serializes")
}
