//! The TypeScript binding is generated from the same IR as `aex-wire`.

use aex_contract_gen::generate_to_memory;
use aex_contract_gen::load::{load, repo_root};

/// One generated file, as text.
fn generated(path: &str) -> String {
    let tree = generate_to_memory(&repo_root()).expect("generate");
    String::from_utf8(
        tree.bytes(path)
            .unwrap_or_else(|| panic!("`{path}` is not generated"))
            .to_vec(),
    )
    .expect("generated TypeScript is UTF-8")
}

#[test]
fn every_schema_has_one_typescript_validator_and_type() {
    let root = repo_root();
    let ir = load(&root).expect("load contract IR");
    let tree = generate_to_memory(&root).expect("generate");
    let source = String::from_utf8(
        tree.bytes("packages/wire/src/generated/models.ts")
            .expect("TypeScript binding")
            .to_vec(),
    )
    .expect("generated TypeScript is UTF-8");

    for schema in ir.schemas.values() {
        assert!(
            source.contains(&format!("export const {}Schema", schema.id)),
            "{} has no generated validator",
            schema.id
        );
        assert!(
            source.contains(&format!("export type {} =", schema.id))
                || source.contains(&format!("export interface {} {{", schema.id)),
            "{} has no generated type",
            schema.id
        );
    }
}

#[test]
fn generated_typescript_keeps_the_closed_wire_invariants() {
    let tree = generate_to_memory(&repo_root()).expect("generate");
    let source = String::from_utf8(
        tree.bytes("packages/wire/src/generated/models.ts")
            .expect("TypeScript binding")
            .to_vec(),
    )
    .expect("generated TypeScript is UTF-8");

    assert!(
        source.contains("}).strict();"),
        "objects must reject unknown fields"
    );
    assert!(
        source.contains("z.discriminatedUnion"),
        "tagged unions must reject unknown arms"
    );
    assert!(
        source.contains("isUuidV7Body"),
        "identifier validation must check UUIDv7 bits, not just spelling"
    );
    assert!(
        source.contains("isId(\"workspace\", value)"),
        "schema identifier fields must share the UUIDv7 validator"
    );
    assert!(
        source.contains("UTF-8 bytes"),
        "text bounds must use wire byte lengths"
    );
}

#[test]
fn the_sdk_route_table_carries_every_operation_the_contract_declares() {
    let ir = load(&repo_root()).expect("load contract IR");
    let source = generated("packages/sdk/src/generated/routes.ts");

    for operation in ir.operations() {
        assert!(
            source.contains(&format!("  | \"{}\"\n", operation.id))
                || source.contains(&format!("  | \"{}\";\n", operation.id)),
            "{} is missing from the SDK `RouteId` union",
            operation.id
        );
        assert!(
            source.contains(&format!("    id: \"{}\",\n", operation.id)),
            "{} has no SDK route descriptor",
            operation.id
        );
        assert!(
            source.contains(&format!("    path: \"{}\",\n", operation.path)),
            "{} has no SDK path",
            operation.id
        );
    }
}

#[test]
fn the_sdk_error_vocabulary_carries_every_code_and_class() {
    let ir = load(&repo_root()).expect("load contract IR");
    let source = generated("packages/sdk/src/generated/errors.ts");

    for row in &ir.errors {
        assert!(
            source.contains(&format!(
                "    {}: {{ class: \"{}\" }},\n",
                row.code, row.class
            )),
            "`{}` has no SDK error metadata row",
            row.code
        );
    }
}

#[test]
fn the_generated_sdk_sources_import_nothing() {
    // `@aexhq/sdk` is published with an empty `dependencies` map. That is why
    // the route table is emitted into the package instead of imported from
    // `@aexhq/wire`, and an emitted `import` would quietly undo it.
    for path in [
        "packages/sdk/src/generated/routes.ts",
        "packages/sdk/src/generated/errors.ts",
    ] {
        let source = generated(path);
        assert!(
            !source.contains("import "),
            "`{path}` imports; the SDK must stay dependency-free"
        );
        assert!(
            source.starts_with("// @generated by aex-contract-gen; DO NOT EDIT.\n"),
            "`{path}` does not open with the repository's generated marker"
        );
    }
}
