//! Regenerates the checked-in models.dev admit table.
//!
//! Run with `bun scripts/gen-models.ts` from the repository root. Reads the
//! vendored `release/models-dev/api.json` snapshot and emits
//! `crates/aex-model-catalog/src/generated/admit.rs`. CI runs this and
//! `git diff --exit-code` to prove the committed table matches the pinned
//! snapshot.

// Ordered to match `aex_wire::provider::ProviderId`'s enum order, so the
// generated table is sorted for binary-search admission.
const PROVIDERS = [
  "openai",
  "anthropic",
  "deepseek",
  "zai",
  "moonshotai",
  "google",
  "openrouter",
  "vercel",
] as const;

type ProviderKey = (typeof PROVIDERS)[number];

const PROVIDER_ID: Record<ProviderKey, string> = {
  openai: "Openai",
  anthropic: "Anthropic",
  google: "Google",
  deepseek: "Deepseek",
  zai: "Zai",
  moonshotai: "Moonshotai",
  openrouter: "Openrouter",
  vercel: "VercelAiGateway",
};

const DIALECT_CLASS: Record<ProviderKey, string> = {
  openai: "OpenAiResponses",
  anthropic: "AnthropicMessages",
  google: "GeminiGenerateContent",
  deepseek: "DeepSeekChat",
  zai: "ZaiChat",
  moonshotai: "MoonshotChat",
  openrouter: "OpenRouterChat",
  vercel: "VercelAiGatewayChat",
};

// models.dev omits an `api` field for the providers whose base URL is fixed by
// their SDK; the compiled defaults below are those SDKs' fixed origins.
const BASE_URL_DEFAULTS: Partial<Record<ProviderKey, string>> = {
  openai: "https://api.openai.com/v1",
  anthropic: "https://api.anthropic.com/v1",
  google: "https://generativelanguage.googleapis.com/v1beta",
  vercel: "https://ai-gateway.vercel.sh/v1",
};

const SNAPSHOT_PATH = "release/models-dev/api.json";
const OUT_PATH = "crates/aex-model-catalog/src/generated/admit.rs";
const DIGEST_PATH = "scripts/models.digest";

function escape(text: string): string {
  return JSON.stringify(text);
}

const data = await Bun.file(SNAPSHOT_PATH).json();

type Row = {
  provider: string;
  provider_id: string;
  model: string;
  context_window_tokens: number;
  max_output_tokens: number;
  tools: boolean;
  parallel_tools: boolean;
  dialect: string;
};

type Meta = {
  provider_id: string;
  base_url: string;
  api_from_models_dev: boolean;
};

const rows: Row[] = [];
const metas: Meta[] = [];

for (const key of PROVIDERS) {
  const provider = data[key];
  if (!provider) {
    throw new Error(`provider ${key} missing from the snapshot`);
  }
  const baseUrl: string | undefined = provider.api ?? BASE_URL_DEFAULTS[key];
  if (!baseUrl) {
    throw new Error(`no base url resolvable for ${key}`);
  }
  metas.push({
    provider_id: PROVIDER_ID[key],
    base_url: baseUrl,
    api_from_models_dev: provider.api !== undefined,
  });
  for (const [id, model] of Object.entries<any>(provider.models)) {
    const limit = model.limit ?? {};
    if (typeof limit.context !== "number" || typeof limit.output !== "number") {
      throw new Error(`bad limit on ${key}/${id}: ${JSON.stringify(limit)}`);
    }
    if (typeof model.tool_call !== "boolean") {
      throw new Error(`bad tool_call on ${key}/${id}`);
    }
    rows.push({
      provider: key,
      provider_id: PROVIDER_ID[key],
      model: id,
      context_window_tokens: limit.context,
      max_output_tokens: limit.output,
      tools: model.tool_call,
      // models.dev publishes no per-model parallel-tool capability. Every
      // tool-capable row is therefore admitted for parallel tool requests;
      // providers that only serialize tool calls simply call them in order.
      parallel_tools: model.tool_call,
      dialect: DIALECT_CLASS[key],
    });
  }
}

// Sort in Rust `&str` byte order (binary search in admit() compares bytes);
// locale-aware collation would disagree on the `~`-prefixed gateway ids.
rows.sort((left, right) =>
  left.provider === right.provider
    ? left.model < right.model
      ? -1
      : left.model > right.model
        ? 1
        : 0
    : PROVIDERS.indexOf(left.provider as any) -
      PROVIDERS.indexOf(right.provider as any),
);

const snapshotBytes = await Bun.file(SNAPSHOT_PATH).arrayBuffer();
const digestBytes = new Uint8Array(
  await crypto.subtle.digest("SHA-256", snapshotBytes),
);
const digest = Array.from(digestBytes)
  .map((byte) => byte.toString(16).padStart(2, "0"))
  .join("");

const lines: string[] = [
  "// @generated by scripts/gen-models.ts — do not edit by hand.",
  `// Source: the models.dev snapshot pinned by ${DIGEST_PATH} (sha256 ${digest}).`,
  "//! The compiled models.dev admit table: identity, limits, tool capability,",
  "//! and the dialect class of every admitted model row.",
  "#![allow(",
  "    missing_docs,",
  "    clippy::unreadable_literal,",
  '    reason = "generated rows are data, not API"',
  ")]",
  "",
  "use aex_model_vocabulary::DialectClass;",
  "use aex_wire::provider::ProviderId;",
  "",
  "/// One compiled provider family: its public wire identity and fixed origin.",
  "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
  "pub struct ProviderMeta {",
  "    pub provider: ProviderId,",
  "    pub base_url: &'static str,",
  "    pub api_from_models_dev: bool,",
  "}",
  "",
  "/// One compiled, admitted model row.",
  "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
  "pub struct AdmittedModel {",
  "    pub provider: ProviderId,",
  "    pub model: &'static str,",
  "    pub context_window_tokens: u32,",
  "    pub max_output_tokens: u32,",
  "    pub tools: bool,",
  "    pub parallel_tools: bool,",
  "    pub dialect: DialectClass,",
  "}",
  "",
  "/// Every provider family in the compiled table, in admit order.",
  "pub const PROVIDERS: &[ProviderMeta] = &[",
];
for (const meta of metas) {
  lines.push(
    "    ProviderMeta {",
    `        provider: ProviderId::${meta.provider_id},`,
    `        base_url: ${escape(meta.base_url)},`,
    `        api_from_models_dev: ${meta.api_from_models_dev},`,
    "    },",
  );
}
lines.push("];");
lines.push("");
lines.push("/// Every admitted model row, sorted by (provider, model id).");
lines.push("pub const MODELS: &[AdmittedModel] = &[");
for (const row of rows) {
  lines.push(
    "    AdmittedModel {",
    `        provider: ProviderId::${row.provider_id},`,
    `        model: ${escape(row.model)},`,
    `        context_window_tokens: ${row.context_window_tokens},`,
    `        max_output_tokens: ${row.max_output_tokens},`,
    `        tools: ${row.tools},`,
    `        parallel_tools: ${row.parallel_tools},`,
    `        dialect: DialectClass::${row.dialect},`,
    "    },",
  );
}
lines.push("];");
lines.push("");
lines.push(`pub const GENERATED_FROM_SHA256: &str =`);
lines.push(`    ${escape(digest)};`);
lines.push("");
lines.push(`/// The snapshot digest as bytes, for the compile-time revision identity.`);
lines.push(`pub const SNAPSHOT_DIGEST: [u8; 32] = [`);
const digestHex = Array.from(digestBytes)
  .map((byte) => `0x${byte.toString(16).padStart(2, "0")}`);
for (let offset = 0; offset < digestHex.length; offset += 16) {
  lines.push(`    ${digestHex.slice(offset, offset + 16).join(", ")},`);
}
lines.push("];");
lines.push("");

await Bun.write(OUT_PATH, lines.join("\n"));

const byProvider = new Map<string, number>();
for (const row of rows) {
  byProvider.set(row.provider, (byProvider.get(row.provider) ?? 0) + 1);
}

console.log(`total_rows=${rows.length}`);
console.log(`generated_bytes=${Buffer.byteLength(lines.join("\n"))}`);
for (const [provider, count] of byProvider) {
  console.log(`rows_${provider}=${count}`);
}
console.log(`tool_call_true=${rows.filter((row) => row.tools).length}`);
console.log(`tool_call_false=${rows.filter((row) => !row.tools).length}`);
